name: form_generator
description: "Form Generator Flutter App"
publish_to: 'taylanyildz@outlook.com'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  uuid: ^4.4.2
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5
  dotted_border: ^2.1.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  expandable: ^5.0.1
  logger: ^2.4.0
  image_picker: ^1.1.2
  syncfusion_flutter_datepicker: ^26.2.10
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svgs/